apiVersion: v1
kind: Pod
metadata: 
  name: nginx-2
  labels:
     type: front-end
spec:
  containers:
     - name: nginx-2
       image: nginx
       resources:
         requests:
           memory: "0.7Gi"
           cpu: "1.5"
